### ISSUE TITLE
Strange HomeKit behavior if light supports both color and temperature

### ISSUE THREAD

**Issue by josiasmontag** [cellcortex/homebridge-yeelighter#10]
I am experiencing exactly this "bug" / behaviour of HomeKit:

https://github.com/home-assistant/core/pull/30756

This problem causes the ambient light control to be not reliable. It forgets the presets etc.

A solution would be to just disable the `ColorTemperature` characteristic for the background light. I think this is the best solution because you typically only use the color feature and not the temperature feature of the background light.

**Comment by atr00** [comment]
I can't get it working with ceiling20 (GuangCan). It has a background light and a moon mode. The moon mode is working perfectly but the background light colour presets will be forgotten and defaulted to CT.
I tried with and without the beta function (Allow CT to be set for RGB lights)
