### ISSUE TITLE
Help Needed: Remove a removed light from the plugin

### ISSUE THREAD

**Issue by AlexKusnezov** [cellcortex/homebridge-yeelighter#100]
Hey guys, yesterday I discovered that a yeelight bulb was broken, so I removed it from the app. Unfortunately it's still in the plugin.
I tried to ignore the light by id in the plugins' settings, but it doesn't work. I only can ignore lights when they are online
How can I remove it, can you help me?

**Comment by cellcortex** [comment]
You can clear the cached Accessories in Homebridge. This should remove all lights and re-detect those that you still have. See: https://github.com/oznu/homebridge-config-ui-x/issues/525
