### ISSUE TITLE
v2.4.10 version doesn't exist

### ISSUE THREAD

**Issue by JinboMa** [cellcortex/homebridge-yeelighter#107]
`npm i homebridge-yeelighter@2.4.10 -g`

npm ERR! code ETARGET
npm ERR! notarget No matching version found for homebridge-yeelighter@2.4.10.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

node: v16.6.0
npm: 7.19.0

`npm i homebridge-yeelighter@latest -g` is v2.4.8

**Comment by cellcortex** [comment]
not sure what I can do here. Can you check 2.4.20
