### ISSUE TITLE
How to get id number from xiomi\yeelight app?

### ISSUE THREAD

**Issue by mor-sound** [cellcortex/homebridge-yeelighter#111]
Hi,
I'm trying to config the plugin, 
but I cant find the bulb id from both apps,

I have w3.

**Comment by jbg** [comment]
I have the same issue - current Yeelight app does not seem to show any identifier matching the pattern required by yeelighter's settings (`^0x[0-9a-fA-F]{16}`). The only identifiers shown in the "Device Info" screen are IP address, MAC address and model.

**Comment by cpaig** [comment]
You can find a value called device Did (like 590012345) in the more device information in the Mi Home(米家) app, convert it to hexadecimal and add 0x00000000 in front, it should be work.

你可以在米家app中的更多设备信息里找到一个叫设备Did的值（像590012345），将他转换成16进制入并在前面加上0x00000000，这样应该就可以了

**Comment by cpaig** [comment]
You can find a value called device Did (like 590012345) in the more device information in the Mi Home(米家) app, convert it to hexadecimal and add 0x00000000 in front, it should be work.

你可以在米家app中的更多设备信息里找到一个叫设备Did的值（像590012345），将他转换成16进制入并在前面加上0x00000000，这样应该就可以了

**Comment by jcr-** [comment]
This seems to no longer be true. I cannot get the device number from the Mi Home app replacement (Xiomi Home) nor from the Yeelight Classic app.
