### ISSUE TITLE
Lights not responding after random time since yeelighter v2.5.5

### ISSUE THREAD

**Issue by chakamad** [cellcortex/homebridge-yeelighter#113]
Dear Supports and Thomas

since the new version the lights do not work after a Radom time. No configuration done in Homebridge.
I have as well the with light that was added in versions 2,5,5 but the most time that lights are switched of via power switch and not connected to the WLAN.. Any help or tip that I could try to fix the issue.
Need to restart Homebridge 2-3 times a day.
![E47A8EB8-73CB-4FC5-86ED-D8306B3601B7](https://user-images.githubusercontent.com/75042849/168944698-17b5a9d8-b222-4247-b7f5-268ecec1c855.png)
![8E454ED2-3317-4068-84CD-B00AB96B99AC](https://user-images.githubusercontent.com/75042849/168944709-f9826055-f3b3-44e4-ab47-fc5192aeeabf.png)

Using Homebridge Version 1.4.1 and Node.js Version | v16.14.2.

**Comment by Weidav** [comment]
I'm experiencing the same problem after the latest update.
Did anybody look into this?

**Comment by Weidav** [comment]
For me this happened once a day, I just went back to 2.4.24 and see if that works.

**Comment by cellcortex** [comment]
should be fixed in the latest release. Sorry it took so long...
