### ISSUE TITLE
ingoring device with corrupt DeviceInfo?

### ISSUE THREAD

**Issue by luggi83** [cellcortex/homebridge-yeelighter#115]
Hi,

I have a swinging ceiling light that works in the Yeelight app. It's also worked in homebridge for a while, but for some reason, I get the below error in the homebridge log. I've tried emptying the device cache, un- and reinstalling the plugin and even reset and re-added the ceiling light in the yeelight app. Any pointers?

Error msg:

[20.5.2022, 12:21:51] [Yeelighter] adding 1 manual accessories
[20.5.2022, 12:21:51] [Yeelighter] ingoring device with corrupt DeviceInfo {
  location: 'yeelight://undefined',
  id: undefined,
  model: undefined,
  support: undefined,
  power: false,
  bright: 0,
  color_mode: -1,
  ct: 0,
  rgb: 'string',
  hue: 0,
  sat: 0,
  host: 'string',
  port: 0,
  debug: false,
  trackedAttributes: [],
  fw_ver: '0,0.0',
  name: 'string'
}
Se

**Comment by radlohac** [comment]
I have the same issue. How did you solve it?

**Comment by luggi83** [comment]
Im Oase to habe to report it went away by itself during the move to the latest rasbian, node, homebridge(-ui) etc, so I can’t really put my finger anywhere. To be save I also hardware reset (IIRC switching and off five times in rapid succession) the lamp and added it to the yeelight app fresh.

**Comment by Ottiver** [comment]
I'm having the same issue. 

Worked very well, then went to the error message after a reboot. Managed to roll of the dice get it reconnected by rebooting homebridge many times. But now can't get it to connect again after a necessary reboot. Device is a yeelight led screen light bar pro. 

Any help would be appreciated, its' great when it works. 


error message is:

[12/1/2023, 3:40:07 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-tuya) is running on port 41726.
[12/1/2023, 3:40:07 PM] [Yeelighter] Loading accessory from cache: 0x000000001e4b6566 (lamp15)
[12/1/2023, 3:40:07 PM] [Yeelighter] adding 1 manual accessories
[12/1/2023, 3:40:07 PM] [Yeelighter] ingoring device with corrupt DeviceInfo {
  location: 'yeelight://undefined',
  id: undefined,
  model: undefined,
  support: undefined,
  power: false,
  bright: 0,
  color_mode: -1,
  ct: 0,
  rgb: 'string',
  hue: 0,
  sat: 0,
  host: 'undefined',
  port: 55443,
  debug: false,
  trackedAttributes: [],
  fw_ver: '0,0.0',
  name: 'string'
}
[12/1/2023, 3:40:07 PM] Homebridge v1.7.0 (HAP v0.11.1) (Yeelighter) is running on port 53513.


===
config is:

 {
            "name": "Yeelighter",
            "timeout": 5000,
            "interval": 60000,
            "ctforcolor": true,
            "blocking": true,
            "split": false,
            "override": [
                {
                    "id": "0x000000000538ac1e",
                    "ignored": true
                },
                {
                    "id": "0x00000000124dc835",
                    "ignored": true
                },
                {
                    "id": "0x000000001e4b6566",
                    "backgroundLight": true,
                    "nightLight": true,
                    "colorTemperature": {
                        "min": 2700,
                        "max": 6500
                    }
                }
            ],
            "manual": [
                {
                    "ignorePower": false
                }
            ],
            "_bridge": {
                "username": "0E:25:00:EC:56:FD",
                "port": 53513
            },
            "platform": "Yeelighter"

**Comment by cellcortex** [comment]
Make sure that the manual section in your settings is empty. Now you have one item there which is triggering this warning. 

Your config should be: 
...
"manual": []
...
