### ISSUE TITLE
How to reduce logs for Yeelighter?

### ISSUE THREAD

**Issue by dukobpa3** [cellcortex/homebridge-yeelighter#118]
I don't need to see regular pings there. Only some changes.

<img width="815" alt="Screenshot 2022-06-03 at 12 00 23" src="https://user-images.githubusercontent.com/1858880/171823743-0f2b658a-09de-45e4-81b9-a7eb9c1104fd.png">

**Comment by uswong** [comment]
Just about to suggest to suppress those logs and got an update from the author today! Thanks.

**Comment by janhicken** [comment]
Seems to be fixed with 4c7f33e9270f4033782bb8720ffb714ff4f43f39, part of release `v2.5.6`
