### ISSUE TITLE
Yeelight Staria Bedside Lamp Pro (Night Mode) Issues

### ISSUE THREAD

**Issue by Marfre888** [cellcortex/homebridge-yeelighter#120]
Hi,

I have a Yeelight Staria Bedside Lamp. It natively supports Homekit, however, I want to run it through this plugin so I am able to have both the normal and night modes inside of Homekit and on one tile. This works rather well, however, I'm running into a problem when I'm asking the lamp to change into night mode. The problem experienced is that the lamp starts off at max power, then dims down to the required level. This is fine for the first time it is changed. However, if you keep calling up the same scene, it continues to change to 100% and then dim down. 

Would it not be possible for the plugin to remember that the lamp was already set in night mode and simply turn on the lamp.

Video attached below for reference. Here I am toggling on and off the same scene.

https://user-images.githubusercontent.com/63603736/174573098-c586d9e4-dbd3-4fdc-a320-505d35f62610.mp4

**Comment by cellcortex** [comment]
Is this still happening? If it does, can you enable detailed debug log for this light and snap those logs here so I can have a look?

**Comment by cellcortex** [comment]
I cannot reproduce this anymore.
