### ISSUE TITLE
Yeelighter settings lags 

### ISSUE THREAD

**Issue by omer-daniel** [cellcortex/homebridge-yeelighter#121]
Hi,
When I open the settings in yeeligher, the menu stuck and I can't press any button.

Please help,
Thanks!

Node.js Version | v16.15.1
-- | --
homebridge-yeelighter v2.5.5 (2022-04-22)

**Comment by omer-daniel** [comment]
Bump

**Comment by cellcortex** [comment]
No idea. The settings aren't part of the plugin. Maybe this is an issue with your Homebridge UI?
