### ISSUE TITLE
Yeelighter  - Error and loops

### ISSUE THREAD

**Issue by shorzi** [cellcortex/homebridge-yeelighter#124]
I did a Homebridge restart today, and it started getting into infinite loops with the Yeelighter plugin causing the problem:
 got these errors:

*This plugin threw an error from the characteristic 'Color Temperature': Characteristic Property 'maxValue' must be a finite number, received "Infinity" (number). See https://homebridge.io/w/JtMGR for more info.

* [0x000000001573976d] Error returned for request [2]: {"code":-1,"message":"client quota exceeded"} []
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".

I've installed multiple alternate versions and it doesn't work...

P.S
I've also updated my Node.js to v16.17.1 and ita still doesn't work

Thanks,

**Comment by shorzi** [comment]
[0x000000001573976d] Error returned for request [2]: {"code":-1,"message":"client quota exceeded"} []
UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".

**Comment by galangel** [comment]
+1

**Comment by cellcortex** [comment]
There isn't much I can do here. There seems to be a rate limit on the yeelights WIFI API. So if you do too many requests in a short period, you run into this error.

**Comment by cellcortex** [comment]
(the error  Characteristic Property 'maxValue' must be a finite number, received "Infinity" seems to stem from a mis-configuration of the `colorTemperature` in the settings. You probably set this to 0.
