### ISSUE TITLE
Can't find device id.

### ISSUE THREAD

**Issue by backll** [cellcortex/homebridge-yeelighter#131]
There's no information how i can get the device id. Someone help me please.

**Comment by cpaig** [comment]
You can find a value called device Did (like 590012345) in the more device information in the Mi Home(米家) app, convert it to hexadecimal and  add 0x00000000 in front, it should be work.

你可以在米家app中的更多设备信息里找到一个叫设备Did的值（像590012345），将他转换成16进制入并在前面加上0x00000000，这样应该就可以了

**Comment by cpaig** [comment]
You can find a value called device Did (like 590012345) in the more device information in the Mi Home(米家) app, convert it to hexadecimal and add 0x00000000 in front, it should be work.

你可以在米家app中的更多设备信息里找到一个叫设备Did的值（像590012345），将他转换成16进制入并在前面加上0x00000000，这样应该就可以了

**Comment by mboeru** [comment]
I had the same issue, what I did to find the device ID was to use another app to discover it
```bash
# Install this package
➜  ~  npm i -g yeelight-manager

# Run this command for discovery
➜  ~ yee list
10:34:13 info:Discovery: Discovery started...
10:34:14 info:Discovery:
┌────────────────────┬──────┬─────────────────────┬─────┬──────┬───────┬────────────┐
│ DeviceID           │ Name │ IP                  │ On? │ Mode │ Value │ Brightness │
├────────────────────┼──────┼─────────────────────┼─────┼──────┼───────┼────────────┤
│ 0x000000001c1c0df │      │ 192.168.144.57:55443 │ No  │ CT   │ 2957  │ 1          │
└────────────────────┴──────┴─────────────────────┴─────┴──────┴───────┴────────────┘
```
Note: you must have LAN Control enabled on your light 

I hope this help you
