### ISSUE TITLE
Constant log of "retry in 5s" after upgrading to 2.5.16

### ISSUE THREAD

**Issue by maisun** [cellcortex/homebridge-yeelighter#140]
Hi,
After upgrading from 2.5.6 to 2.5.16 I notice my homebridge log is filled with "retry in 5s" from the plugin.
Would it be possible to turn the debug log off? I think the log is from below code (line 138):
https://github.com/cellcortex/homebridge-yeelighter/blob/master/src/yeedevice.ts

Many thanks in advance!

**Comment by maisun** [comment]
Hi thank you! Has this been released? Just tried version 2.6.0 and still see lots of warning messages "retry in 5s"...

**Comment by Prodigio** [comment]
@cellcortex is it released with v2.6.0? I do see the "retry in 5s" filling my log, and not the new log message "retrying to connect in 5s".

I just found the file `yeedevice.js` on my device, which is still the old version.
