### ISSUE TITLE
Ambient Light 

### ISSUE THREAD

**Issue by Strawqens** [cellcortex/homebridge-yeelighter#153]
The Ambient Light in Yeelight Arwen lamps works unpredictably, misrepresents colors, and Mi Home (Miot) app works better. The 320 Pro lamp only has a yellow hue, it doesn’t even detect correct names, and the plug is essentially useless for ceiling lamps.

**Comment by cellcortex** [comment]
Appreciate that you went through providing this highly valuable issue report. I hope writing this helped you more than it helped me with improving this plugin.
