### ISSUE TITLE
onDeviceUpdate() getting undefined input

### ISSUE THREAD

**Issue by NMAC427** [cellcortex/homebridge-yeelighter#18]
I'm not exactly sure what the `onDeviceUpdate` function of the `Light` class is supposed to do, but the three input parameters (id, result, error) always seem to be undefined. Because this function gets called when the yeelight sends a notification to the socket, there only really should be one input parameter: the message.

I managed to get the function working by replacing it with the following implementation:

```javascript
this.onDeviceUpdate = (result) => {
    if (result["params"] === undefined) {
        return;
    }

     // Copy the current attributes, because the yeelight message only contains the attributes that changed.
    const newAttributes = JSON.parse(JSON.stringify(this.attributes));
    for (const key of Object.keys(this.attributes)) {
        if (!(key in result["params"])) {
            continue;
        }

        switch (typeof lightservice_1.EMPTY_ATTRIBUTES[key]) {
            case "number":
                newAttributes[key] = Number(result["params"][key]);
                break;
            case "boolean":
                newAttributes[key] = result["params"][key] == "on";
                break;
            default:
                newAttributes[key] = result["params"][key];
                break;
        }
    }

    this.updateTimestamp = Date.now();
    this.onUpdateAttributes(newAttributes);
};
```

Because I'm not very familiar with the codebase and have not experience with javascript / typescript, it would be best, if someone who knows how js works, could reimplement this cleanly.

**Comment by cellcortex** [comment]
The typescript/javascript is correct. My guess is that your JavaScript engine is too old to comprehend some the "destructuring assignment" there. Can you verify your version of node and update? This is an ES6 feature.

**Comment by NMAC427** [comment]
I'm running homebridge in the [oznu/homebridge](https://registry.hub.docker.com/r/oznu/homebridge) docker, which comes with v12.16.1 of node. According to the readme.md this repo requires at least v10.0.0.

Should I try updating to node 14 and see if it works then?
ps: I'm using the bedside lamp 2.
