### ISSUE TITLE
Down Light White Ambience Range

### ISSUE THREAD

**Issue by markaragnos81** [cellcortex/homebridge-yeelighter#2]
Your Plugin works very well. Thanks so far.
I figured out that the White Ambience Down light can not switch color ranges...please see attached image
![88A10944-D273-4A97-9528-4CB2635D18A9](https://user-images.githubusercontent.com/59516224/72205256-28505400-3481-11ea-8e63-1d88f86301c1.png)

**Comment by cellcortex** [comment]
Can you paste the log from the start of home bridge - or a snapshot of the device name in the home apps device details. I need the name of the device to try to reproduce this.
