### ISSUE TITLE
Mi LED Smart Bulb - First light up in red

### ISSUE THREAD

**Issue by 62fixolab** [cellcortex/homebridge-yeelighter#20]
If I set bulb color to white (Temperature), when I shut off the bulb and proceed to turn it on I turn on red.
And if I set a color purple (Color) for example, everything works perfect.

The problem is when you set Temperature light, on Color light is fine.

![photo_2020-04-18_06-37-47](https://user-images.githubusercontent.com/12599130/79628197-28768480-813f-11ea-931b-058f13a8f504.jpg)

**Comment by flareman** [comment]
Same issue here, I set up Homebridge and the Yeeligher plugin with the default configuration. I have two color Yeelight 1st gen bulbs and they work right with the Yeelight application: default color setting works, that color comes back when they are switched off and on from the wall switch. When turning the bulbs on and off from the Home app though, they come back to the last color setting they had, not the white light setting I have set in the Yeelight app. Likewise, if the bulbs are switched off then on again from the wall switch, then after turning them on via Home app, they will light up red.

**Comment by 62fixolab** [comment]
@flareman I'm using 1st gen too of this bulbs

**Comment by cellcortex** [comment]
Can you try the "ctforcolor" setting and see if that changes things?

**Comment by 62fixolab** [comment]
> Can you try the "ctforcolor" setting and see if that changes things?

How I try this ?

**Comment by Yuke-hd** [comment]
in plugin config, check "Allow CT to be set for RGB lights"

**Comment by flareman** [comment]
> Can you try the "ctforcolor" setting and see if that changes things?

Works kind of better: now the lamp does not come back to previous colour when it is switched back on, either from the switch or from HomeKit, and it seems to update between the YeeLight app and Home.app.

There is the issue of color templates in Home.app: when you tap a color preset inside the lamp details and tap it again to set it to another color/brightness hue, then tap back to another preset, then back to the previous one, sometimes it does overwrites the first preset slot with the values of the second one. However, at least the light works relatively reliably now so good job.

PS: The plugin has the old getters behavior enabled by default. I'm using it with the new behavior and had no issues as far as I can tell. Is there a reason for this?

**Comment by 62fixolab** [comment]
> in plugin config, check "Allow CT to be set for RGB lights"

Testing with this enabled and disabled. Same results.
I bought a Yeelight Bedside Lamp 2 and I'm getting same results.
It's happening on Lights that has Temperature and Color options.
