### ISSUE TITLE
Retrieving attributes failed. Using last attributes. [ 'timeout' ]

### ISSUE THREAD

**Issue by simaotx** [cellcortex/homebridge-yeelighter#21]
I set up homebridge on raspberry pi 4 and installed yeelighter and I'm always seeing this error [0x0000000007c1d722] retrieving attributes failed. Using the last attributes. [ 'timeout' ], despite the light still works on the home app. I have also noticed that I can´t set any scene with my yeelight. I always get an error at the end.

**Comment by Kvothet** [comment]
Did you find why it happens? Having the same problem.

**Comment by simaotx** [comment]
No, already tried to clean install homebridge and the plugin and still happens

**Comment by fevlake** [comment]
Same here.

**Comment by SimWhite** [comment]
Same here. Using clean installation without any additional plugins.

**Comment by cellcortex** [comment]
Latest version should fix this.
