### ISSUE TITLE
Manual Adding

### ISSUE THREAD

**Issue by no-Legend** [cellcortex/homebridge-yeelighter#23]
Hi,

First thanks for your work.
I have my bedside lamps into a vlan.
The vlan is called smarthome and the Norma lan is acceable to this smarthome vlan.

Your plugin is in this case not possible to search for this device and will also not automatically add them.

Is it possible to add them manual to the config like the override?

Cheers Robert

**Comment by S474N** [comment]
How router do you have?

**Comment by no-Legend** [comment]
> How router do you have?

I use opnsense on a alix apu2.
In my network I use three VLANs.
One is the normal internal network, one is for smart home devices and the last one is for guest.
All have different ip ranges, and gateways.

**Comment by S474N** [comment]
I think, that I have same problem :)

https://github.com/cellcortex/homebridge-yeelighter/issues/24

**Comment by cellcortex** [comment]
Yeelighter is using this API: https://www.yeelight.com/download/Yeelight_Inter-Operation_Spec.pdf 
They have some detail on the registration protocol. I would suggest to try to solve this at the network config level by forwarding/opening ports for this. 

If this cannot be fixed at the gateway, I would also accept a PR for the config.
