### ISSUE TITLE
Default

### ISSUE THREAD

**Issue by dhanzseros** [cellcortex/homebridge-yeelighter#26]
I cannot switch back to default white, or warm light with 100% brightness after I choose a color. I have to launch Home Assistant to switch back or the original app. Colors are working fine. With another plugin it worked exactly the opposite :)

**Comment by cellcortex** [comment]
Is this for an RGB light? Can you play with the "ctforcolor" setting and see if that improves things?

**Comment by dhanzseros** [comment]
Hey! Thank you for the tip! It works! I did not know it has more settings on the plugin surface :)
