### ISSUE TITLE
Sorry - I had the same issue. Version 1.3.1 should solve this.

### ISSUE THREAD

**Issue by Sungamm** [cellcortex/homebridge-yeelighter#28]
Sorry - I had the same issue. Version 1.3.1 should solve this.

_Originally posted by @cellcortex in https://github.com/cellcortex/homebridge-yeelighter/issues/27#issuecomment-633040740_

I already use 1.3.1 but it still cause a lots of warns. There is no update available. Can you ha a look into this, please. 

Greets

**Comment by cellcortex** [comment]
I believe I found the issue - also added some extra logging. Can you update to 1.3.4 ?

**Comment by Sungamm** [comment]
Perfect work! Thank you for your effort and friedly help! Great plug-in and I am glad that you sharing it with us!
