### ISSUE TITLE
Enhancement - name in Name

### ISSUE THREAD

**Issue by S474N** [cellcortex/homebridge-yeelighter#29]
If user have defined "name" in override light option in config.json, is possible to add this name also to "Name" in UI-X? And the same name is visible in HomeKit. 

Now shows Serial Number in Name and also in HomeKit..

![image](https://user-images.githubusercontent.com/16512337/82754639-906b5b00-9dce-11ea-8492-3f8667a0ddba.png)

**Comment by cellcortex** [comment]
can be added to the config. It kinda has to be unique.

**Comment by cellcortex** [comment]
Not sure what tool you're using by yeelighter is now setting a name (version 1.5.9)

**Comment by S474N** [comment]
Still have 0x00..... in Name :(

**Comment by S474N** [comment]
Now is Name in Name, but I thought Name of device in Accessories :)

**Comment by cellcortex** [comment]
Can you re-check this with the latest version. I believe to have finally sorted out the name setting.

**Comment by S474N** [comment]
Sorry, because I have problems with VLAN and "_no direct IP support_" I switched all lights completely to Nodered.
