### ISSUE TITLE
Status wrong when turning on from config-ui-x

### ISSUE THREAD

**Issue by bottlebug** [cellcortex/homebridge-yeelighter#30]
I currently am using this plugin with the Yeelight bulb and bedside lamp.

I try to turn them on from config-ui-x, the lights turn on, however, the status still shows off.
On Home.app however, it shows the correct status. I also can't turn it off too from the platform.

If I turn them on from Home.app, it's working as expected and the correct status is also shown on config-ui-x

**Comment by S474N** [comment]
Same problem for me! There is delay between change status.

If you wait about 20s, will status change?

**Comment by bottlebug** [comment]
Just tried it and looks like it changes to what it should be after 20 seconds.

**Comment by slcr** [comment]
+1

**Comment by cellcortex** [comment]
I tried to derive some state directly when it is set to emulate how the HomeKit UI does it.

**Comment by paqpaqpaq** [comment]
Same here. Sometimes it takes 20 sec, sometimes 50.
Quite strange

**Comment by cellcortex** [comment]
Couldn't really reproduce this. I made quite some changes on the whole naming and characteristic setting recently. So it might be resolved with recent updates.
