### ISSUE TITLE
Doesn't support Yeelight20 (YLXD50YL)

### ISSUE THREAD

**Issue by eliac7** [cellcortex/homebridge-yeelighter#32]
```
[6/6/2020, 12:50:34 PM] [Yeelighter] Initializing Yeelighter platform...
[6/6/2020, 12:50:34 PM] Failed to find plugin to handle accessory ceiling20-xxxxx
[6/6/2020, 12:50:34 PM] Removing orphaned accessory ceiling20-xxxxx
```

These are the attributes I got from the discover_bulbs of Yeelight python package  if that helps

`[{'ip': 'XXXXXX', 'port': 55443, 'capabilities': {'id': '0x00000000XXXXXX', 'model': 'ceiling20', 'fw_ver': '20', 'support': 'get_prop set_default set_power toggle set_bright set_scene cron_add cron_get cron_del start_cf stop_cf set_ct_abx set_name set_adjust adjust_bright adjust_ct bg_set_rgb bg_set_hsv bg_set_ct_abx bg_start_cf bg_stop_cf set_scene_bundle bg_set_default bg_set_power bg_set_bright bg_set_adjust bg_adjust_bright bg_adjust_color bg_adjust_ct bg_toggle dev_toggle', 'power': 'on', 'bright': '100', 'color_mode': '2', 'ct': '6500', 'rgb': '0', 'hue': '0', 'sat': '0', 'name': ''}}]`

**Comment by alert82** [comment]
I have it running with the YLXD50YL and its working here

**Comment by cellcortex** [comment]
Looks more like your homebridge has a corrupted device cache. Can you delete the cache directory of your homebridge and try again?

**Comment by eliac7** [comment]
Thanks for your answers. I format Homebridge and installed the image for the Raspberry Pi and now works perfectly. Thanks for your time.
