### ISSUE TITLE
Feature Request: Yeelight Meteorite

### ISSUE THREAD

**Issue by Leololololo** [cellcortex/homebridge-yeelighter#33]
Hi, 
just because you wrote FeatureRequest welcome. I would love to be able to use my Yeelight Meteor Lights. Is there any hope for me?

![meteorite](https://user-images.githubusercontent.com/63395206/84516329-f06a6880-accd-11ea-8310-2cdab17f6deb.jpg)

**Comment by cellcortex** [comment]
I believe it should just work. Don't have one myself but I'm confident it will somewhat work out of the box. The rest can be tweaked.

**Comment by lyance** [comment]
Update:  this basically works with my Yeelight Meteorite - just downloaded today's version.  I'm able to control the downlight (temp, brightness, on/off) and separately the background light (temp, colour, brightness, on/off).  The only issue I've found is that it doesn't remember the background light colour/temp settings after editing it.  Almost perfect!

**Comment by Leololololo** [comment]
@lyance @cellcortex I finaly setupped my whole homebridge again and now i actually got it to work too. Thank you for giving me hope ;) Main lights react snappy but i cant turn it off via klicking on the icon but instead i have to klick on it and pull the brightness all the way up to 100% or 0%, is there anything i can configure so that i can just click on it?

The Backround lights show up in homebridge but not yet in my home app, also i can turn a light on or off once and then they dont react for about 30 sec anymore. Also no way to switch colors.

 
![Meteorite](https://user-images.githubusercontent.com/63395206/87760151-a2d2a580-c80f-11ea-817d-69a6a8e8dcae.png)
![Bildschirmfoto 2020-07-17 um 09 21 08](https://user-images.githubusercontent.com/63395206/87760160-a5cd9600-c80f-11ea-8baa-cce580b0d24e.png)
