### ISSUE TITLE
Ceiling Lamp - Disconnects and reconnects after some seconds

### ISSUE THREAD

**Issue by eliac7** [cellcortex/homebridge-yeelighter#34]
![2020-06-16-23_58_31-Window](https://user-images.githubusercontent.com/26083840/84827772-a0710600-b02d-11ea-8c42-19ab049d82ce.jpg)

As you can see from the above screenshot, my ceiling lamp is getting disconnected and reconnected. I tried to reset it and reconnect to the WiFi but doesn't seem to help at all. Any ideas?

**Comment by cellcortex** [comment]
Did you disable the development interface?
