### ISSUE TITLE
Light naming

### ISSUE THREAD

**Issue by netzpixel** [cellcortex/homebridge-yeelighter#35]
The naming is a bit strange. I can change the name for the logs, but nut for anything else? I tried to use this plugin with alexa, but all the bulbs have the same name, so only one is available in alexa... Can you maybe fix this?

**Comment by cellcortex** [comment]
Version 1.5.9 sets the initial name. The name itself is managed by HomeKit so you may have to clear the cache for it to work. Also if you edited the name in HomeKit, this will overwrite what the plugin sets for the accessory. 
Generally the names are managed by HomeKit and not by the devices.
