### ISSUE TITLE
offOnDisconnect not working

### ISSUE THREAD

**Issue by sqsuica** [cellcortex/homebridge-yeelighter#37]
Hi,

I am having trouble to get the option offOnDisconnect to work.
I have added the device id under the settings on the homebridge config ui x. Restarted the homebridge. 

Steps:
Turned on the physical light switch and checked that the lights are showing ON in Home app.

Expected:
Turned off the physical light switch, expecting that the lights are changed to OFF.

Actual:
Waited for 5 mins and the lights were still showing as ON

Homebridge version 1.1.1
Yeelighter 1.5.12

**Comment by nitaybz** [comment]
I can confirm it's not working for me too...

**Comment by maisun** [comment]
Same here....

**Comment by maisun** [comment]
Any plan to fix this?
