### ISSUE TITLE
All homebridge devices shows "No answer" when one is powered off

### ISSUE THREAD

**Issue by Paulxp** [cellcortex/homebridge-yeelighter#4]
Hi,
I have multiple LED strips and Ceiling lights 650 at home. From time to time my wife shutdown light with old school wall switch. So it means, that device is completely off and disconnected from network. Old plugin which i used yeeelight-platform showed "No answer" ony at that one device. I was able to control other devices. 

But with your plugin, when one device is switched off by interrupting power, i can't control any other devices in Homebridge. All devices has "No answer" status. When i power on again last device, evreything works normally. Is there option how to manage that state? Thanx.

P.S.: I am planning to buy smart switches to avoid this problem.

**Comment by cellcortex** [comment]
I believe this should be fixed with the latest releases. However I plan to switch to a different approach for reading status from the yeelights since homebridge seems to hang when waiting for a response from getting a characteristic

**Comment by Paulxp** [comment]
Sorry, i forget to give feedback. Yes, it works fine. Issue has been fixed. Thank your for good job.
