### ISSUE TITLE
Override ignored devices does not works

### ISSUE THREAD

**Issue by myluna08** [cellcortex/homebridge-yeelighter#42]
Dear all,

I have three devices, and I want to hide two devices in HomeKit app.
I check yeelight app and verify that this devices has not been enabled control-in-lan
I added and array to my config with ignored parameter and restart homebridge but devices still appears. 

I delete cached accessories and restart again but does not works.
Here's my config

`        {
            "name": "Yeelighter",
            "timeout": 5000,
            "interval": 60000,
            "ctforcolor": true,
            "blocking": false,
            "split": false,
            "override": [
                {
                    "id": "0x0000000018374aef",
                    "name": "Bedside_Lamp",
                    "useNameAsId": false,
                    "ignored": true
                },
                {
                    "id": "0x0000000064484a8",
                    "name": "Entrance_Lamp",
                    "useNameAsId": false,
                    "ignored": true
                }
            ],
            "platform": "Yeelighter"
        }`

What can I do to delete this two devices from homebridge ??
Thanks

**Comment by BaRaD5** [comment]
did you try reinstalling the plugin?
do you have other yeelight related plugins installed?

works fine for me...

**Comment by Zver5** [comment]
same problem, devices are not ignored

**Comment by cellcortex** [comment]
you could delete the cachedAccessories file in your homebridge installation.
