### ISSUE TITLE
Bedside Lamp

### ISSUE THREAD

**Issue by Giuliosa63** [cellcortex/homebridge-yeelighter#43]
Hi,
I'm trying to configure my Bedside Lamp. It seems to work fine in "override mode", but I would like to try an already tested configuration. Which is a suggested value for Minimal and Maximum Color temperature?
Thanks

**Comment by cellcortex** [comment]
can you post the logs from homebridge and also which lamp exactly you have? The color temperature range will have to be found out by reading some specs.

**Comment by Giuliosa63** [comment]
I'm sorry but I have sent the Bedisde Lamp back to Amazon due to erratic behaviour.
