### ISSUE TITLE
Automatic Colour Temperature function

### ISSUE THREAD

**Issue by atr00** [cellcortex/homebridge-yeelighter#45]
Hi,
Would it be possible to add the new Apple feature that automatically sets the colour temperature depending on the time?
That would be amazing.

Thanks
Alessandro

**Comment by kurtdwarwick** [comment]
Hi

Seconded for this feature. Homebridge 1.3.0 has Adaptive Lighting "built-in" and each plugin can leverage that.

That would probably be the easiest way to achieve the feature. 

It would certainly be awesome!

Kurt

**Comment by cellcortex** [comment]
This should kinda work. Still the color lights still have a somewhat broken HSV support - I haven't figured a way to properly convert the HSV into RGB.
