### ISSUE TITLE
Please add support for ceiling13, ceiling14, ceiling18

### ISSUE THREAD

**Issue by ProphetRush** [cellcortex/homebridge-yeelighter#46]
As mentioned at the title, ceiling13, ceiling14, ceiling18 is not fully supported by the plugin. 
* Color temputure adjustment  is not working at all model
* Moonlight mode is not working at ceiling18. If the moonlight mode is enabled in override config, all controls for ceiling18 will not be affected.
*  For 13 and 14, the moonlight mode can be activated, but after that, I can't change it back to normal mode in Homekit by pulling up the lightness, the light will just blink one time, and the lightness shown in Homekit will changed back to original one after few secs.

So please add supported for ceiling13, ceiling14 and ceiling18 model if possible, thx a lot!

**Comment by ProphetRush** [comment]
[11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: sendCommand(28, set_power, ["on","sudden",0,5]) []
[11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] sent command 28: set_power []
[11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: sendCommand(29, set_power, ["on","smooth",500,1]) []
[11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] sent command 29: set_power []
[11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: transaction 28 took 0.194s [ { id: 28, result: [ 'ok' ] } ]
[11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: received 28: OK []
[11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: Moonlight on []
[11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: sendCommand(30, set_bright, [62,"sudden",0]) []
[11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] sent command 30: set_bright []
[11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: transaction 29 took 0.215s [ { id: 29, result: [ 'ok' ] } ]
[11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: received 29: OK []
[11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: transaction 30 took 0.089s [ { id: 30, result: [ 'ok' ] } ]
[11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: received 30: OK []


It seems like a async concurrent issue, the command 30 set brightness will execute before command29's execution.

**Comment by cellcortex** [comment]
Can you tell me which lights the ceiling13, ceiling14, ceiling18 map to and which features should be supported?

**Comment by cellcortex** [comment]
> [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: sendCommand(28, set_power, ["on","sudden",0,5]) []
> [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] sent command 28: set_power []
> [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: sendCommand(29, set_power, ["on","smooth",500,1]) []
> [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] sent command 29: set_power []
> [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: transaction 28 took 0.194s [ { id: 28, result: [ 'ok' ] } ]
> [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: received 28: OK []
> [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: Moonlight on []
> [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: sendCommand(30, set_bright, [62,"sudden",0]) []
> [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] sent command 30: set_bright []
> [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: transaction 29 took 0.215s [ { id: 29, result: [ 'ok' ] } ]
> [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: received 29: OK []
> [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: transaction 30 took 0.089s [ { id: 30, result: [ 'ok' ] } ]
> [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: received 30: OK []
> 
> It seems like a async concurrent issue, the command 30 set brightness will execute before command29's execution.

This looks like a separate issue from the one above.

**Comment by ProphetRush** [comment]
Thx for the fast reply, here's the spec I found on aqura's aliexpress page

A2001R900
Color temperature of lamp beads: 2700K, 6500K
Applicable area: 25-35m2
Color rendering index: whole lamp Ra 95@4000K
Rated power: 95W
 
A2001C550
Color temperature of lamp beads: 2700K, 6500K
Applicable area: 15-25m2
Color rendering index: whole lamp Ra 95@4000K
Rated power: 50W
 
A2001C450
Product size: φ495x93mm
Color temperature of lamp beads: 2700K, 6500K
Applicable area: 10-15m²
Color rendering index: whole lamp Ra 95@4000K
Rated power: 50W

They should mapped to ceiling18, 13 and 14 in above order, and moonlight mode should be supported for all of them.

**Comment by ProphetRush** [comment]
> > [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: sendCommand(28, set_power, ["on","sudden",0,5]) []
> > [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] sent command 28: set_power []
> > [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: sendCommand(29, set_power, ["on","smooth",500,1]) []
> > [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] sent command 29: set_power []
> > [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: transaction 28 took 0.194s [ { id: 28, result: [ 'ok' ] } ]
> > [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: received 28: OK []
> > [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: Moonlight on []
> > [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: sendCommand(30, set_bright, [62,"sudden",0]) []
> > [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] sent command 30: set_bright []
> > [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: transaction 29 took 0.215s [ { id: 29, result: [ 'ok' ] } ]
> > [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: received 29: OK []
> > [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: transaction 30 took 0.089s [ { id: 30, result: [ 'ok' ] } ]
> > [11/24/2020, 12:01:11 AM] [Yeelighter] [BedroomLight] debug: received 30: OK []
> > It seems like a async concurrent issue, the command 30 set brightness will execute before command29's execution.
> 
> This looks like a separate issue from the one above.

Yes this maybe a separate issue. I didn't enable the detailed logging yesterday so I thought it is just an unsupport issue at the first time.
