### ISSUE TITLE
Everything broken with 2.2.0

### ISSUE THREAD

**Issue by plantoschka** [cellcortex/homebridge-yeelighter#49]
Just updated to 2.2.0 and all my lights appear twice with one of them with a „main“ name. Controlling the lights is not possible.

![0DDFC2E8-3BBB-41BB-97E8-7B377EBCB0EE](https://user-images.githubusercontent.com/2125129/100551053-b04c7180-327e-11eb-8651-7e1de49ac364.jpeg)

**Comment by Terminator0007** [comment]
Even after 2.2.4 update my Yeelight Ceiling Light ( Jiaoyue 650 ) stop working .... I need to back with 1.5.16 ver. In 2.2.4 ver I get 2 buttons more, main and background but no response both .... Therefore now finally back to 1.5.16. ..........

**Comment by cellcortex** [comment]
Sorry - made a big update to the latest style of doing plugins. This should ultimately allow for more flexibility with names and choosing the composition of accessories. Somehow I messed things up. I believe things should be working okay from version 2.2.8 onwards. Sorry for the inconvenience.

For the duplicate services (main/background) - I may not be able to fully prevent that from happening once when going from 1.x to 2.x. To fix it, please delete the cache in homebridge: https://github.com/oznu/homebridge-config-ui-x/issues/525

**Comment by Terminator0007** [comment]
Now it works ok. But the last update I see 2.2.9 .... Thanks for info.
