### ISSUE TITLE
Strange behaviour in newest version

### ISSUE THREAD

**Issue by fklement** [cellcortex/homebridge-yeelighter#50]
Could you please elaborate on why I have now two of the controller per accessory?
<img width="552" alt="Screenshot 2020-11-30 at 20 58 29" src="https://user-images.githubusercontent.com/7302097/100658097-d04b6600-334e-11eb-8680-9ef323ed08e3.png">

Also just clicking the symbol to turn or off doesn't work anymore for me.
<img width="230" alt="Screenshot 2020-11-30 at 20 59 47" src="https://user-images.githubusercontent.com/7302097/100658209-fbce5080-334e-11eb-8d39-2ef7ea7e8b7e.png">

**Comment by cellcortex** [comment]
Hi,

Version 2 has changed the layout of accessories towards home ridge. Clearing the home bridge cache once should solve this.

Cheers

**Comment by fklement** [comment]
@cellcortex Thank you. Clearing the cache for those devices solved it.
