### ISSUE TITLE
update to 2.2.11 new strange device appears

### ISSUE THREAD

**Issue by Sungamm** [cellcortex/homebridge-yeelighter#51]
Hello,

I installed the latest update (2.2.11) and cannot control my yeelight 480 anymore. But I have a new strange device with the name
"0x0000000007c55bb7 main". In Homebridge itself I can turn on and off the yeelight with this. But with the Apple Homekit I can change the color (white only) but the light did not turn on. 

Therefore I go back to the 1.5.16 and the good old yeelight 480 apears again and I am able to control via homebridge and apple homekit. But the strange device "0x0000000007c55bb7 main" is still there?!?

I removed the cachedaccesories folder allready but strange device is still there (in Homebridge as in Apple Homekit). 

Do have anyone a tip if I do anything wrong or is that a bug?

**Comment by Sungamm** [comment]
ok, I was able to get rid of the strange 0x000 device. Stop homebridge and use 

`sudo rm -rf /var/homebridge/accessories`
afterwards sudo reboot

The strange device is gone than. I tried to update to 2.2.11 again and had the same issue. No control of the yeelight but a strange device 0x00000 in Homebridge and Apple Homekit. In Homekit I am not able to control the yeelight anymore. I am go back to 1.5.16 and there there. Its fine for me.

**Comment by Staubgeborener** [comment]
Can confirm this. I have exactly the same problem with the last update 2.2.11. I also did a downgrade with `npm install -g homebridge-yeelighter@1.5.16`, restarted the Homebridge and now everything works again.

But I would keep this issue open as this is not a real solution.

**Comment by Sungamm** [comment]
Due to the fact that I am not alone with the issue, I allow myself to reopen it

**Comment by cellcortex** [comment]
Can you purge the cachedAccessories in home bridge? I believe the problem is just that the format of the accessory has changed between 1.x and 2.x.

With homebridge-config-ui:
https://github.com/oznu/homebridge-config-ui-x/issues/525

With plain home bridge, remove the cachedAccessories file from your home bridge config directory and restart.

**Comment by Sungamm** [comment]
> 
> 
> Can you purge the cachedAccessories in home bridge? I believe the problem is just that the format of the accessory has changed between 1.x and 2.x.
> 
> With homebridge-config-ui:
> [oznu/homebridge-config-ui-x#525](https://github.com/oznu/homebridge-config-ui-x/issues/525)
> 
> With plain home bridge, remove the cachedAccessories file from your home bridge config directory and restart.

Hi, 
for me it did not work. If I update to 2.2.11 I have the strange device starting (name) with 0x0000... 

After use 
sudo rm -rf /var/homebridge/accessories

nothing changed. The strange device is still there. The mayor problem is, the original device (yeelight480) is not responsing. The new one I can change in Apple Homekit but there is no react. Light did not get on or off. 

But if I used the homebridge-config GUI I can turn on and off the light with the 0x0000 device. But not any longer with the yeelight480 device. Switching back to 1.5.16 and use

sudo rm -rf /var/homebridge/accessories

its all fine. Currently I find no way to update to 2.x

Maybe I have to remove the plugin (old one?), use "sudo rm -rf /var/homebridge/accessories" and reboot. Then the old device must be gone. Afterwards install the new one and test it. But all Apple Homekit automations must be created afterwards :-( 

Therefore I will try that on Weekend only.

**Comment by Staubgeborener** [comment]
@Sungamm Did you try this out?

**Comment by Sungamm** [comment]
> 
> 
> @Sungamm Did you try this out?

Yes, I did it for few seconds. 

I used 2.3.4 from Yeelighter plugin and after install the plug-in I shutdown Homebridge and use 
sudo rm -rf /var/homebridge/accessories
After restart all is fine for me :-)

@cellcortex Thank you for your great work!

**Comment by cellcortex** [comment]
great. Happy this finally worked out. Sorry the transition to be a bit "bumpy".

**Comment by Staubgeborener** [comment]
> I used 2.3.4 from Yeelighter plugin and after install the plug-in I shutdown Homebridge and use
> sudo rm -rf /var/homebridge/accessories
> After restart all is fine for me :-)

I can confirm this with `v2.3.6`. I could not controll my bedside lamp without removing the accessories. Now everything works fine.
