### ISSUE TITLE
erased lights 

### ISSUE THREAD

**Issue by firebird2006** [cellcortex/homebridge-yeelighter#55]
Hey, 
erased lights. will not be erased you see them always in Hoobs. 
Please fix bug with sync with yeelight app.

In Yeelightight app are no lights. But you can not clear in Hoobs

**Comment by cellcortex** [comment]
Yeelighter is not connecting to the Yeelight App. It is connecting to the lights directly. I don't know hoobs, but I guess this is an issue that should be reported with that...

**Comment by firebird2006** [comment]
Ok there is no option to erase  it from homebridge. 
Because the Lamp is out of Order so there is no more an option to connect any time more to the lamp. 
I´ve just the switch in HOOBS / Home bridge 
thanks
