### ISSUE TITLE
requesting attributes in the log non-stop

### ISSUE THREAD

**Issue by galoiring** [cellcortex/homebridge-yeelighter#56]
I get this on the log non-stop and it fill my log
yeelight bulb S1

<img width="940" alt="צילום מסך 2020-12-06 ב-12 34 28" src="https://user-images.githubusercontent.com/74841666/101277765-648a5280-37bf-11eb-824f-84a81bbc61f7.png">

**Comment by cellcortex** [comment]
fixed in 2.2.12

**Comment by galoiring** [comment]
> fixed in 2.2.12

what do you mean ?

**Comment by galoiring** [comment]
I update the version but still continue

**Comment by galoiring** [comment]
<img width="939" alt="צילום מסך 2020-12-06 ב-20 20 57" src="https://user-images.githubusercontent.com/74841666/101288710-abe50300-3800-11eb-9581-2a0718406102.png">

**Comment by cellcortex** [comment]
hmm... seems your homebridge has debug logging enabled. I would recommend to set the log level to info. I want to keep these detailed log messages in for debugging issues. So unfortunately won't fix this on this end...

**Comment by galoiring** [comment]
<img width="1275" alt="צילום מסך 2020-12-09 ב-8 20 54" src="https://user-images.githubusercontent.com/74841666/101592758-76eed100-39f7-11eb-92fd-4698a54a67b1.png">
<img width="1270" alt="צילום מסך 2020-12-09 ב-8 21 11" src="https://user-images.githubusercontent.com/74841666/101592791-8110cf80-39f7-11eb-8fb4-ffd257c04c46.png">

actually it is disable ...
