### ISSUE TITLE
Plugin does not detect my yeelight

### ISSUE THREAD

**Issue by IceFlom** [cellcortex/homebridge-yeelighter#6]
Hi,
I have to install and activate the plugin and then it should autodiscover my yeelights, right? I installed it with the "homebridge-config-ui-x" and I can see in the logs that it's loaded and that it's starting an "auto discovery". But after that I don't see anything else from the plugin in the logs and I don't get my lightstrip in homekit.
I have only one lightstrip, called "Original Xiaomi Yeelight Smart Light Strip - RGB Color". I'm using it since more than a year with an Amazon Echo and I can see it in the Yeelight app. LAN mode is activated.

Logs:
Feb 09 21:42:21 raspi4 homebridge[18347]: [2020-2-9 21:42:21] Loaded config.json with 0 accessories and 3 platforms.
Feb 09 21:42:21 raspi4 homebridge[18347]: [2020-2-9 21:42:21] ---
Feb 09 21:42:21 raspi4 homebridge[18347]: [2020-2-9 21:42:21] Loaded plugin: homebridge-config-ui-x
Feb 09 21:42:21 raspi4 homebridge[18347]: [2020-2-9 21:42:21] Registering platform 'homebridge-config-ui-x.config'
Feb 09 21:42:21 raspi4 homebridge[18347]: [2020-2-9 21:42:21] ---
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] Loaded plugin: homebridge-hue
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] Registering platform 'homebridge-hue.Hue'
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] ---
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] Loaded plugin: homebridge-yeelighter
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] Registering platform 'homebridge-yeelighter.Yeelighter'
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] ---
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] Loading 3 platforms...
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] [Config] Initializing config platform...
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] [Config] Spawning homebridge-config-ui-x with PID 18371
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] [Hue] Initializing Hue platform...
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] [Hue] homebridge-hue v0.11.52, node v12.15.0, homebridge v0.4.50
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] [Yeelighter] Initializing Yeelighter platform...
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] Loading 0 accessories...
Feb 09 21:42:22 raspi4 homebridge[18347]: [2020-2-9 21:42:22] [Yeelighter] ** Discovery Started **
Feb 09 21:42:25 raspi4 homebridge[18347]: [2020-2-9 21:42:25] [Config] Homebridge Config UI X v4.10.0 is listening on :: port 8080
Feb 09 21:42:27 raspi4 homebridge[18347]: [2020-2-9 21:42:27] [Hue] Philips hue: Philips BSB002 bridge v1935144040, api v1.35.0
Feb 09 21:42:28 raspi4 homebridge[18347]: [2020-2-9 21:42:28] [Hue] Philips hue: 4 accessories
Feb 09 21:42:28 raspi4 homebridge[18347]: [2020-2-9 21:42:28] [Hue] masked debug info dumped to /var/homebridge/homebridge-hue.json.gz
Feb 09 21:42:28 raspi4 homebridge[18347]: [2020-2-9 21:42:28] [Hue] Initializing platform accessory 'Philips hue'...
Feb 09 21:42:28 raspi4 homebridge[18347]: [2020-2-9 21:42:28] [Hue] Philips hue: 2 services
Feb 09 21:42:28 raspi4 homebridge[18347]: [2020-2-9 21:42:28] [Hue] Initializing platform accessory 'Flur2'...
Feb 09 21:42:28 raspi4 homebridge[18347]: [2020-2-9 21:42:28] [Hue] Initializing platform accessory 'VorneLinks'...
Feb 09 21:42:28 raspi4 homebridge[18347]: [2020-2-9 21:42:28] [Hue] Initializing platform accessory 'Flur1'...
Feb 09 21:42:28 raspi4 homebridge[18347]: Setup Payload:
Feb 09 21:42:28 raspi4 homebridge[18347]: X-HM://0023MNTMY8EC3
Feb 09 21:42:28 raspi4 homebridge[18347]: Scan this code with your HomeKit app on your iOS device to pair with Homebridge:
...

**Comment by IceFlom** [comment]
Ok, it was my fault. Seems that ufw was blocking it. I don't know how to allow the udp broadcasting packets for the yeelight, but after disabling the firewall temporarily the stripe was found by the plugin.

**Comment by cellcortex** [comment]
UDP multicast goes to 239.255.255.250:1982

Maybe that helps.
