### ISSUE TITLE
New Yeelight Device - Monitor Hanging Light

### ISSUE THREAD

**Issue by Hyejeongdd** [cellcortex/homebridge-yeelighter#62]
This is Yeelight new light product and it can enable "LAN control", I can use your plugin to add it in HomeKit. But look like have something wrong.

Product Model: lamp15
Response Sample: {"power":true,"color_mode":2,"bright":100,"hue":194,"sat":87,"ct":3800,"bg_power":false,"bg_bright":100,"bg_hue":194,"bg_sat":87,"bg_ct":2703,"bg_lmode":1,"nl_br":0,"active_mode":0,"name":""}

This product have 2 lights. In front of light is screen light, color temperature support 2700k - 6500k. another one is backgroundLight, it is a RGB light.

Waiting for your reply.

**Comment by henocookie** [comment]
It automatically grouped the front and back (ambient) lights into one light group for me in the Apple Home app. You can separate this and show as two separate "tiles" if you want.

![IMG_0752](https://user-images.githubusercontent.com/52792328/106023376-a7312280-60be-11eb-8c79-29c3eb4f5c55.jpeg)
![IMG_0753](https://user-images.githubusercontent.com/52792328/106023386-a8fae600-60be-11eb-9829-c12b1674d06e.PNG)
![IMG_0754](https://user-images.githubusercontent.com/52792328/106023391-aa2c1300-60be-11eb-9774-693655b025ab.PNG)

**Comment by cellcortex** [comment]
support added

**Comment by louliangsheng** [comment]
@cellcortex  Hello，the current brightness of the device follows the brightness rules when the moonlight mode is turned on, but this device does not support the moonlight mode, but even after I disable the moonlight mode, its brightness is not normal, I hope you can fix it.
And the screen light and backgroundLight can be independent, and one can be turned off separately, but at present, if the backgroundLight is turned on, the screen light cannot be turned off.
In addition, I found that this plugin generates too many logs. Even if false is set, there are still a lot of logs generated. Can you stop non-warning logs from being generated?
