### ISSUE TITLE
My yeelight dont understand "rouge" color

### ISSUE THREAD

**Issue by cucupidon** [cellcortex/homebridge-yeelighter#64]
Strangely, when I ask siri to change the color of my yeelight for "rouge" (Red in french), the color does not change. It understand all other colors but not red. I have a new homekit compatible yeelight 1s and it understands "red" while all those which are controlled by yeelighter do not change color.
If I do it manually through the app it works fine, only the voice command produces this error.

**Comment by AdictiK** [comment]
Hello, I have exactly the same problem, the red (Rouge).
Some colors like "magenta", "brown", "fuchsia" do not work.
Finally if I say "white" the command is executed but nothing happens I am required to specify "warm white" or "cold white".
Cordially.

**Comment by cellcortex** [comment]
No idea what this may be but Yeelighter is not involved in the converting words to colors. It gets RGB/HSV values from homekit. I dont think there's anything that can be done on this end.

**Comment by anon1338** [comment]
Having the same issue with the 1s bulb. With other homebridge plugins it works (e.g. homebridge-yeelight-wifi). Can this issue be reopened?

**Comment by anon1338** [comment]
I found out that treating the light as an hsv light solves the issue
