### ISSUE TITLE
Homebridge 1.3 is now in beta with AdaptiveLightingController. Any plan to include this feature in the plugin?

### ISSUE THREAD

**Issue by Aekung** [cellcortex/homebridge-yeelighter#68]
Hi,

Homebridge 1.3.x is now in beta. One of its key features is to support Adaptive Lighting with AdaptiveLightingController for the plugin developer to use. Are you planning to update this plugin to support the Adaptive Lighting?

By the way, thank you very much for this amazing plugin. =)

**Comment by galoiring** [comment]
this is great pluging and I hope too it will added so I won't need to look out for other plugin

**Comment by okonet** [comment]
I tried adding it but I could not yet understand where it should be done. Need to spend more time looking at the code. At the same time I published this feature in https://github.com/vieira/homebridge-yeelight-wifi

**Comment by cellcortex** [comment]
I've added basic support now. Sorry this took so long - had a busy year.
