### ISSUE TITLE
BLE Gateway

### ISSUE THREAD

**Issue by mrmaximas** [cellcortex/homebridge-yeelighter#7]
What about reading data from Mi Hygrothermograph connected via Mi Bedside Lamp BLE gateway?

**Comment by Sungamm** [comment]
Push! That will be great. No chance to use the BLE gateway with European server. If that can grab via plug-in will be great!

**Comment by cellcortex** [comment]
Unfortunately this is not supported with the interface that this plugin uses. Yeelight would have to adapt their API.

**Comment by Sungamm** [comment]
Ah, ok. Thank you for your Feedback and your good work with the Plugin!
