### ISSUE TITLE
offOnDisconnect doesn’t take effect

### ISSUE THREAD

**Issue by maisun** [cellcortex/homebridge-yeelighter#72]
Hi,
I’d like to report a potential bug - offOnDisconnect setting doesn’t seem to work in my setup. I have tried to change the value to true/false and get the same result.

**Comment by BaRaD5** [comment]
#37

**Comment by Shoshkin** [comment]
#91 might solve the issue

**Comment by maisun** [comment]
> #91 might solve the issue

Looks like the issue isn't fixed by this..

**Comment by cellcortex** [comment]
I believe this should have been fixed.
