### ISSUE TITLE
compatibility?

### ISSUE THREAD

**Issue by g3nsvrv** [cellcortex/homebridge-yeelighter#73]
This app works with xiaomi lights which are basically yeelights but under another brand? specifically lightbulb essentials.

Also, theres a way to use tokens instead of ids?

**Comment by cellcortex** [comment]
This plugin uses the LAN control API for Yeelights which Xiaomi lights do not support. There isn't much that could be used from this plugins code to support the different API that Xiaomi has - maybe there is another plugin that can help. I won't be adding it to this one.
