### ISSUE TITLE
YeeLight bulb - max 80% Brightness

### ISSUE THREAD

**Issue by dkpl** [cellcortex/homebridge-yeelighter#83]
I connected the bulb Yeelight E27 YLDP06YL however the maximum brightness setting in homekit is much less bright than from the standard app. It is about 80% of the total brightness from the xiaomi app. Is there any way to change ? I will add that added to homekit natively this bulb also works in the same way. Another modul to homebridge solved this problem.

**Comment by cellcortex** [comment]
That's weird. Since the brightness is set in percent and the value is essentially just forwarded from HomeKit to the Yeelight, I fear there is nothing that can be done at this end.
