### ISSUE TITLE
TypeError: Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by nicolasdevineau** [cellcortex/homebridge-yeelighter#87]
Hello,

Thanks for your plugin.
I just installed it, and when I try to add my yeelight bulb, I get this error:

![image_2021-10-03_214147](https://user-images.githubusercontent.com/38103726/135769046-a0d36ec7-03ae-4a0b-a6f6-fd7712de31a9.png)

My config:

{
    "name": "Yeelighter",
    "timeout": 5000,
    "interval": 60000,
    "ctforcolor": true,
    "blocking": false,
    "split": true,
    "manual": [
        {
            "id": "64:90:C1:B4:5B:E2",
            "address": "192.168.1.47",
            "name": "Ampoule",
            "model": "yeelink.light.color5",
            "log": true,
            "color": true,
            "backgroundLight": true,
            "nightLight": true,
            "separateAmbient": true,
            "colorTemperature": {
                "min": 5000
            }
        }
    ],
    "platform": "Yeelighter"
}

What can I do ?

**Comment by cellcortex** [comment]
The JavaScript version that your node.js is running is too old. It doesn't support some of the features used by yeelighter. You can fix this by updating your node.js.
https://github.com/homebridge/homebridge/wiki/How-To-Update-Node.js

You will need node v. 16 or above
