### ISSUE TITLE
Mi LED Ceiling Light no Moonlight

### ISSUE THREAD

**Issue by ghost** [cellcortex/homebridge-yeelighter#9]
Hello. I trying to get the moonlight working on my Mi LED Ceiling Light i get the folowing in the log when starting up homebridge. I can see that it's not detecting the model and defaults to non moonlight.

[Homebridge] [3/4/2020, 6:05:31 PM] [Yeelighter] [0x0000000007cbb39d] no specs for light 0x0000000007cbb39d ceiling5. It supports: get_prop set_default set_power toggle set_bright set_scene cron_add cron_get cron_del start_cf stop_cf set_ct_abx set_name set_adjust adjust_bright adjust_ct. Using fallback. This will not give you moonlight support. []

I triedto override with moonlight and i get the following

[Homebridge] [3/4/2020, 6:05:31 PM] [Yeelighter] Override config for 0x0000000007cbb39d: {"id":"0x0000000007cbb39d","moonlight":true,"log":true}

But when i turn down the brightness to below 50% it does not switch to moonlight.

I aslo cannot change the colour temperature even though the option is there nothiung happens.

Any ideas? :)

I can get the moonlight to work with this plugin https://www.npmjs.com/package/homebridge-yeelight-wifi

But i rather have your solution that switch auto below 50 instead of a separate switch for moonlight.

**Comment by ghost** [comment]
Seems like i got it working by using nightLight : true instead of moonlight : true

**Comment by cellcortex** [comment]
I added ceiling5 so it should now be supported without special config.
