### ISSUE TITLE
Yeelight Stopped LAN Control

### ISSUE THREAD

**Issue by hamdanfadi** [cellcortex/homebridge-yeelighter#90]
Hi there,
I have Yeelight Bedside, I have updated the firmware last night. LAN Control stopped working. Any solution for that?

**Comment by b2un0** [comment]
Nope, look also here.
Every Yeelights are now useless
https://forum.yeelight.com/t/topic/22664

**Comment by BaRaD5** [comment]
You can solve this issue by getting an android phone (bluestacks could do the trick) and downloading version 3.2.59 of the Yeelight app
that did the trick for me...
Why this version? update came around february '21 from reading these post so this version is one or two releases before the "LANless update"

Source: I have both first and second "mi bedside lamp" seems to do the trick for both.
2nd source: trust me bro

EDIT: i updated my lamp to 0.41 it seems like they FW blocked it from being open to LAN, native homekit is your best bet as far as "mi bedside lamp 2" goes

**Comment by cellcortex** [comment]
Nothing can be done at this end
