### ISSUE TITLE
Can`t add yeelight ceiling light 320

### ISSUE THREAD

**Issue by ograch91** [cellcortex/homebridge-yeelighter#92]
Recently purchased 2 new ceiling light 320,
I have installed the plugin, updated the firmware of the lights enabled the LAN control and gave them static IP address on my router like all other devices. 
The homebridge didn't recognized either of them and the only log I see is this 
**1/3/2022, 6:07:19 PM] [Yeelighter] adding 0 manual accessories**
Couldn't find the identifier on the yeelight app to add them manually, nmp v8.3.0 node v17.3.0

**Comment by cellcortex** [comment]
I believe these newer lights have dropped support for the LAN protocol that this plugin is built around. At least I found other people raising that the support for the LAN protocol is removed in newer firmwares.
If the lights are not detected (nothing in the homebridge logs) I don't think I can do much from this plugins end...
