### ISSUE TITLE
gu10 w1 errors

### ISSUE THREAD

**Issue by ClaLas** [cellcortex/homebridge-yeelighter#94]
I'm trying to get my 2 gu10 w1's bulbs to work but i get these kind of errors in homebridge log and in Home app they not respond:

`[20/01/2022, 14:58:28] [Yeelighter] [0x000000001b1857d6] transaction 8 took 0.057s [ { id: 8, error: { code: -1, message: 'client quota exceeded' } } ]
[20/01/2022, 14:58:28] [Yeelighter] [0x000000001b1857d6] Error returned for request [8]: {"code":-1,"message":"client quota exceeded"} []
(node:16344) UnhandledPromiseRejectionWarning: #<Object>
(node:16344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 9)`

In config.json i've added these lines:

` {
            "platform": "Yeelighter",
            "name": "Yeelighter",
            "timeout": 5000,
            "interval": 60000
        },`

What should i do?

**Comment by chakamad** [comment]
Dear all, I am having similar issues an than Homebridge will go in a restart Loop. The only way to fixed that is to turn the power off the gu 10 white lights. Any hint how to fix that? 

They will work than suddenly I have the bug.

**Comment by chakamad** [comment]
I have 4 of the device and this is my error. Have the same configuration as labirinth30.
My log:

[23/01/2022, 19:22:33] [Yeelighter] (0x000000000edd9b49] Error returned for request [2]: {"code": -1, "message:"client quota exceeded"} [1
[23/01/2022, 19:22:33] UnhandledPromiseRejection: This error originated either by throwing inside of an asyn function without a catch block, or by rejecting a promise which was not handled with .catch).
The promise rejected with the reason"#<Object>
[23/01/2022,
, 19:22:33] Got SIGTERM, shutting down Homebridge.

**Comment by shakedlokits** [comment]
I am experiencing the exact same thing with the same lights

**Comment by cellcortex** [comment]
support added
