### ISSUE TITLE
[Support] Suppress the warning messages

### ISSUE THREAD

**Issue by uswong** [cellcortex/homebridge-yeelighter#99]
Hi, I have 12 Yeelight Ceiling Lights and 5 of them with secondary ambient lights.  The plugins works perfectly for every one of them.  Thanks so much for putting this plugin together .  I have a separate smart switch to turn off the power to each of these  Lights when not in use but the consequence of switching the power off to the lights seem to have created a lot of warnings from the plugins as shown below.  It is filling up my homebridge log screen. Is there a way to suppress those warnings?  

![image](https://user-images.githubusercontent.com/96530237/151284165-fe1f94d0-b469-4c2b-8c40-fc4e8065a5ec.png)

Cheers,
uswong

**Comment by uswong** [comment]
Just found out that to suppress the log, we just need `"log":false` in the config.json.

All sorted now.  

However, I am quite disappointed that no one responded to my request for support.

**Comment by uswong** [comment]
Does anyone in this community has the same issue as mine?

The "log":false is already the default. Setting it explicitly in config.json did not do anything.

Can @cellcortex have a look at this?

**Comment by cellcortex** [comment]
I put some extra safeguards in place with version 2.4.20
